try:
  print(x)
#this will not print as x isn't defined
except:
  print("Something went wrong")
#this will print as it the "try" wont work
finally:
  print("The 'try except' is finished")
#will always print


try:
  print("Hello World")
#this will print as it is a string
except:
  print("thid didn't work")
#this will not print
